resources:
- ./templates/distribution.yaml
images:
- name: registry.syntasso.io/syntasso/k8s-health-agent
  newName: "{{ .Values.imageRegistry.host }}/{{ .Values.imageRegistry.skeOperatorImage.name }}"
  newTag: "{{ .Chart.AppVersion }}"
patches:
  - target:
      kind: Deployment
    patch: |-
      - op: replace
        path: /spec/template/spec/imagePullSecrets
        value:
          - name: '{{ .Values.imageRegistry.imagePullSecret | default "syntasso-registry" }}'
