# [DEPRECATED] Use additionalResources instead
{{- range .Values.destinations }}
---
apiVersion: platform.kratix.io/v1alpha1
kind: Destination
metadata:
  name: {{ .name }}
  labels: {{ toYaml .labels | nindent 4 }}
  annotations:
    helm.sh/hook: "post-install,post-upgrade"
    helm.sh/hook-weight: "5"
spec:
  path: {{ .path }}
  {{- with .filepath }}
  filepath:
    mode: {{ .mode | default "nestedByMetadata" }}
  {{- end}}
  stateStoreRef:
    name: {{ .stateStoreRef.name }}
    kind: {{ .stateStoreRef.kind }}
  strictMatchLabels: {{ .strictMatchLabels | default false}}
{{ end }}
