name: Release SKE Operator Charts

on:
  workflow_dispatch:
  push:
    branches: ['main']
    paths: ['ske-operator/Chart.yaml']

env:
  GITHUB_TOKEN: "${{ secrets.CR_TOKEN }}"
  CR_TOKEN: "${{ secrets.CR_TOKEN }}"

jobs:
  release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "syntassodev"
          git config user.email "kratix@syntasso.io"

      - name: Install Helm
        uses: azure/setup-helm@v3

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.6.0
        with:
          charts_dir: .
          pages_branch: gh-pages
          skip_existing: true
          skip_upload: true

      - name: Check out code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: eu-west-2
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Upload Chart to Releases Bucket
        run: |
          VERSION=$(cat ske-operator/Chart.yaml | grep version: | awk '{print $2}')
          aws s3 cp .cr-release-packages/ske-operator-${VERSION}.tgz ske-operator-helm-chart/${VERSION}/ --dry-run

      # - name: trigger-run-ci
      #   env:
      #     CCI_TOKEN: ${{ secrets.CCI_TOKEN }}
      #     CCI_TARGET_SLUG: ${{ secrets.CCI_TARGET_SLUG }}
      #   run: |
      #     curl -H "Circle-Token: ${CCI_TOKEN}" \
      #       -H 'content-type: application/json' \
      #       -d '{"parameters":{"ske_helm_chart_new_release":true}}' \
      #       https://circleci.com/api/v2/project/${CCI_TARGET_SLUG}/pipeline
