name: Update K8s Health Agent

on:
  workflow_dispatch:

jobs:
  update-k8s-health-agent:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.CR_TOKEN }}

      - name: Install Helm
        uses: azure/setup-helm@v3

      - name: Configure Git
        run: |
          git config user.name "syntassodev"
          git config user.email "kratix@syntasso.io"
  
      - name: Update chart, template and crds
        run: |
          ./scripts/update-k8s-health-agent
        env:
          GH_TOKEN: ${{ secrets.CR_TOKEN }}

      - name: Ensure helm repo has updated
        run: |
          TIMEOUT=100
          ELAPSED=0
          until [ "$(helm search repo syntasso -o json | jq -r '.[] | select(.name=="syntasso/k8s-health-agent").version')" = "$DESIRED_VERSION" ]; do
            if [ $ELAPSED -ge $TIMEOUT ]; then
              echo "Timeout reached."
              exit 1
            fi

            echo "Waiting for repository to update..."
            sleep 10
            ELAPSED=$((ELAPSED + 10))
            helm repo update
          done

      - name: Commit and push changes
        run: |
          git add .
          git commit -m "feat: update K8s Health Agent to the latest released version"
          git push
